# Generated by Django 2.1.1 on 2018-11-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('owner', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
            ],
        ),
    ]
