# Generated by Django 2.1.1 on 2018-11-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_task_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskList',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_list',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(verbose_name='due date'),
        ),
    ]
